from __future__ import annotations

from .constants import (
    _RELATION_KIND_BY_PREDICATE,
    BIOLINK_NS,
    CITO_NS,
    CURIE_PREFIXES,
    DCTERMS_NS,
    DEFAULT_GRAPH_PATH,
    EVIDENCE_STANCE_PREDICATES,
    GRAPH_EXPORT_EDGE_METADATA_PREDICATES,
    GRAPH_EXPORT_SCHEMA_VERSION,
    GRAPH_EXPORT_VISIBLE_LAYERS,
    GRAPH_LAYERS,
    INITIAL_GRAPH_TEMPLATE,
    PREDICATE_REGISTRY,
    PROJECT_ENTITY_PREFIX_KINDS,
    PROJECT_ENTITY_PREFIXES,
    PROJECT_NS,
    REVISION_URI,
    SCHEMA_NS,
    SCI_NS,
    SCIC_NS,
    STRUCTURED_PROPOSITION_PREDICATES,
    VALID_INQUIRY_TYPES,
)
from .dataset import _load_dataset, _save_dataset, init_graph_file, read_graph_stats, save_graph_dataset
from .dot import build_graph_dot
from .evidence_signals import (
    _apply_evidence_semantics_to_bundle,
    _apply_phase1_metadata_to_bundle,
    _collect_evidence_signals,
    _collect_evidence_types,
    _evidence_targets_for_uri,
    _evidence_type_strings,
    _json_literal,
    _linked_claims_for_hypothesis,
    _load_proposition_bridge_hypotheses,
    _load_proposition_evidence_semantics,
    _load_proposition_falsifications,
    _load_proposition_interaction_terms,
    _load_proposition_phase1_metadata,
    _load_proposition_pre_registrations,
    _source_strings,
)
from .export import export_graph_payload
from .graphutil import _has_cycle
from .identity import (
    _about_tokens,
    _derive_relation_claim_text,
    _edge_claims,
    _edge_statement_uri,
    _entity_kind_from_uri,
    _graph_uri,
    _relation_claim_label,
    _resolve_center_entity,
    _resolve_term,
    _short_name,
    _slug,
    canonical_id_from_entity_uri,
    shorten_uri,
)
from .inquiry import (
    get_inquiry,
    list_inquiries,
    list_inquiries_dataset,
    render_inquiry_doc,
    set_treatment_outcome,
    validate_inquiry,
    validate_inquiry_dataset,
)
from .mutations import (
    _attach_edge_claims,
    _warn_on_relation_direction_mismatch,
    add_article,
    add_assumption,
    add_concept,
    add_data_package,
    add_discussion,
    add_edge,
    add_evidence_edge,
    add_falsification,
    add_finding,
    add_hypothesis,
    add_inquiry,
    add_inquiry_edge,
    add_inquiry_node,
    add_interpretation,
    add_mechanism,
    add_observation,
    add_paper_entity,
    add_proposition,
    add_question,
    add_story,
    add_transformation,
    migrate_addresses_direction,
    set_boundary_role,
    set_param_metadata,
)
from .notebooks import _NOTEBOOKS_PYPROJECT, _copy_viz_notebook, _uv_lock
from .queries import query_claims, query_evidence, query_neighborhood
from .snapshot import import_snapshot, stamp_revision
from .summary import (
    _claim_summary_data,
    query_coverage,
    query_dashboard_summary,
    query_gaps,
    query_inquiry_summary,
    query_neighborhood_summary,
    query_project_summary,
    query_question_summary,
    query_uncertainty,
)
from .types import (
    ClaimSummaryData,
    EvidenceClaimBundle,
    EvidenceEdgeOverlay,
    EvidenceOverlayData,
    EvidenceSignalSummary,
    FalsificationRecord,
    InquiryEdge,
    InquiryInfo,
    InquirySummaryData,
    NeighborhoodSummaryData,
    ProjectSummaryData,
    PropositionEvidenceLine,
    PropositionEvidenceSemantics,
    PropositionInteractionTerm,
    PropositionPhase1Metadata,
    QuestionSummaryData,
)
from .validation import (
    diff_graph_inputs,
    diff_graph_inputs_dataset,
    query_predicates,
    validate_graph,
    validate_graph_dataset,
)
