"""Core profile manifest for Science-native knowledge graph semantics."""

from science_model.identity import EntityClass
from science_model.profiles.schema import (
    EntityKind,
    KindCategory,
    ProfileManifest,
    RelationEndpointPair,
    RelationKind,
)

_CONCLUSION_KINDS = [
    "interpretation",
    "finding",
    "discussion",
    "report",
    "validation-report",
    "story",
]

_CONCLUSION_KIND_PAIRS = [
    RelationEndpointPair(source_kind=source_kind, target_kind=target_kind)
    for source_kind in _CONCLUSION_KINDS
    for target_kind in _CONCLUSION_KINDS
]

CORE_PROFILE = ProfileManifest(
    name="core",
    imports=[],
    strictness="core",
    entity_kinds=[
        EntityKind(
            name="hypothesis",
            canonical_prefix="hypothesis",
            layer="layer/core",
            description="Testable project hypothesis.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            shortform="h",
            home="entities/hypotheses",
            strategy="numeric",
            default_status="proposed",
            statuses=[
                "proposed",
                "under-investigation",
                "partially-supported",
                "supported",
                "weakened",
                "refuted",
                "archived",
            ],
        ),
        EntityKind(
            name="question",
            canonical_prefix="question",
            layer="layer/core",
            description="Open or resolved project question.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            shortform="q",
            home="entities/questions",
            strategy="numeric",
            default_status="active",
            statuses=["active", "partially-answered", "answered", "deferred", "retired", "archived"],
        ),
        EntityKind(
            name="research-question",
            canonical_prefix="research-question",
            layer="layer/core",
            description="The project's single guiding research question.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            home="entities/research-question.md",
            strategy="singleton",
        ),
        EntityKind(
            name="task",
            canonical_prefix="task",
            layer="layer/core",
            description="Operational project task tracked in the graph.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="proposition",
            canonical_prefix="proposition",
            layer="layer/core",
            description="Truth-apt statement — the fundamental epistemic unit.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            shortform="p",
            home="entities/propositions",
            strategy="slug",
            default_status="draft",
            statuses=["draft", "active", "supported", "contested", "weakened", "retired", "superseded", "archived"],
        ),
        EntityKind(
            name="observation",
            canonical_prefix="observation",
            layer="layer/core",
            description="Concrete empirical fact anchored to specific data.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/observations",
            strategy="slug",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="finding",
            canonical_prefix="finding",
            layer="layer/core",
            description="Unit of learned knowledge: propositions grounded by observations from an analysis.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/findings",
            strategy="numeric",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="interpretation",
            canonical_prefix="interpretation",
            layer="layer/core",
            description="One analysis session's narrative and its findings.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            shortform="i",
            home="entities/interpretations",
            strategy="numeric",
            default_status="active",
            statuses=["active", "complete", "superseded", "archived"],
        ),
        EntityKind(
            name="story",
            canonical_prefix="story",
            layer="layer/core",
            description="Coherent narrative arc synthesizing interpretations around a question or hypothesis.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/stories",
            strategy="slug",
            default_status="draft",
            statuses=["draft", "developing", "mature"],
        ),
        EntityKind(
            name="synthesis",
            canonical_prefix="synthesis",
            layer="layer/core",
            description="Cross-cutting synthesis rolling up interpretations and findings.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/synthesis",
            strategy="numeric",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="report",
            canonical_prefix="report",
            layer="layer/core",
            description="Standalone written report over project knowledge.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            home="entities/reports",
            strategy="numeric",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="validation-report",
            canonical_prefix="validation-report",
            layer="layer/core",
            description="Report validating an analysis, model, or pipeline result.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="discussion",
            canonical_prefix="discussion",
            layer="layer/core",
            description="Structured critical discussion of a hypothesis, question, or topic.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            shortform="d",
            home="entities/discussions",
            strategy="numeric",
            default_status="active",
            statuses=["active", "complete", "superseded", "archived"],
        ),
        EntityKind(
            name="inquiry",
            canonical_prefix="inquiry",
            layer="layer/core",
            description="A scoped research inquiry (boundary + estimand over the knowledge graph).",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            home="entities/inquiries",
            strategy="numeric",
            default_status="active",
            statuses=["active", "complete", "superseded", "archived"],
        ),
        EntityKind(
            name="mechanism",
            canonical_prefix="mechanism",
            layer="layer/core",
            description="Named explanatory structure linking multiple typed entities and propositions.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/mechanisms",
            strategy="numeric",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="theme",
            canonical_prefix="theme",
            layer="layer/core",
            description="Durable cross-cutting organizing frame linking project questions, hypotheses, tasks, reports, concepts, and guardrails.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            shortform="t",
            home="entities/themes",
            strategy="numeric",
            default_status="active",
            statuses=["draft", "active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="assumption",
            canonical_prefix="assumption",
            layer="layer/core",
            description="An explicit assumption underpinning a model, analysis, or argument.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="patch-definition",
            canonical_prefix="patch-definition",
            layer="layer/core",
            description="Authored patch profile asserting a belief membership over the graph.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            home="entities/patches",
            strategy="slug",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="paper",
            canonical_prefix="paper",
            layer="layer/core",
            description="External literature note for a read, searched, or summarized paper.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/papers",
            strategy="citekey",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="prose-source",
            canonical_prefix="prose-source",
            layer="layer/core",
            description="Authored internal Markdown prose used as an operational evidence source.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/prose-sources",
            strategy="slug",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="book",
            canonical_prefix="book",
            layer="layer/core",
            description="Long-form monograph summarized chapter-by-chapter; an evidence source.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/books",
            strategy="citekey",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="talk",
            canonical_prefix="talk",
            layer="layer/core",
            description="Recorded seminar or conference presentation; an unrefereed evidence source.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/talks",
            strategy="citekey",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="article",
            canonical_prefix="article",
            layer="layer/core",
            description="External article or document referenced as a source.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="concept",
            canonical_prefix="concept",
            layer="layer/core",
            description="A named concept referenced across the project.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/concepts",
            strategy="slug",
            default_status="active",
            statuses=["active", "deprecated"],
        ),
        EntityKind(
            name="construct",
            canonical_prefix="construct",
            layer="layer/core",
            description="A theoretical construct operationalized by the project.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
            home="entities/constructs",
            strategy="slug",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="outcome",
            canonical_prefix="outcome",
            layer="layer/core",
            description="A measured or targeted outcome variable.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
            home="entities/outcomes",
            strategy="slug",
            default_status="active",
            statuses=["active", "retired"],
        ),
        EntityKind(
            name="topic",
            canonical_prefix="topic",
            layer="layer/core",
            description="Legacy research-topic synthesis note; prefer typed semantic entities for new work.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
            home="entities/topics",
            strategy="slug",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="variable",
            canonical_prefix="variable",
            layer="layer/core",
            description="A modeled variable in an analysis or causal model.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="experiment",
            canonical_prefix="experiment",
            layer="layer/core",
            description="Experiment or analysis step that tests project questions.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="method",
            canonical_prefix="method",
            layer="layer/core",
            description="Analytical method or computational approach.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/methods",
            strategy="slug",
            default_status="active",
            statuses=["active", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="pre-registration",
            canonical_prefix="pre-registration",
            layer="layer/core",
            description="Pre-registered analysis plan stating expectations before analysis.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/pre-registrations",
            strategy="numeric",
            default_status="active",
            statuses=["active", "amended", "superseded", "retired"],
        ),
        EntityKind(
            name="plan",
            canonical_prefix="plan",
            layer="layer/core",
            description="An authored implementation or analysis plan.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/plans",
            strategy="numeric",
            default_status="active",
            statuses=["active", "complete", "superseded", "retired", "archived"],
        ),
        EntityKind(
            name="search",
            canonical_prefix="search",
            layer="layer/core",
            description="A literature or dataset search and its recorded results.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/searches",
            strategy="numeric",
            default_status="active",
            statuses=["active", "complete", "retired", "archived"],
        ),
        EntityKind(
            name="decision",
            canonical_prefix="decision",
            layer="layer/core",
            description="A recorded project decision with rationale.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.AUTHORED_CORE,
            home="entities/decision",
            strategy="verbatim",
            default_status="active",
            statuses=["active", "superseded", "abandoned", "archived"],
        ),
        EntityKind(
            name="claim-registry",
            canonical_prefix="claim-registry",
            layer="layer/core",
            description="The project's single registry of tracked external claims.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/claim-registry.yaml",
            strategy="singleton",
        ),
        EntityKind(
            name="spec",
            canonical_prefix="spec",
            layer="layer/core",
            description="A design or implementation specification.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="transformation",
            canonical_prefix="transformation",
            layer="layer/core",
            description="A data transformation applied within an analysis.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="curation-sweep",
            canonical_prefix="curation-sweep",
            layer="layer/core",
            description="A project-memory curation sweep tracked as an operational artifact.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="dataset",
            canonical_prefix="dataset",
            layer="layer/core",
            description="Tabular or file dataset tracked as a research artifact.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/datasets",
            strategy="id-local",
            # Minimal vocabulary covering values in use across projects; refinement
            # of the dataset lifecycle is deferred to the 2026-04-19 lifecycle design.
            default_status="active",
            statuses=["proposed", "candidate", "active", "retired", "deprecated"],
        ),
        EntityKind(
            name="workflow",
            canonical_prefix="workflow",
            layer="layer/core",
            description="Reusable pipeline definition (Snakefile + config + rules).",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/workflows",
            strategy="id-local",
            default_status="active",
            statuses=["planned", "active", "deprecated", "retired"],
        ),
        EntityKind(
            name="workflow-run",
            canonical_prefix="workflow-run",
            layer="layer/core",
            description="Concrete execution of a workflow producing durable outputs.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/workflow-runs",
            strategy="id-local",
            default_status="running",
            statuses=["running", "complete", "failed"],
        ),
        EntityKind(
            name="workflow-step",
            canonical_prefix="workflow-step",
            layer="layer/core",
            description="Individual step within a workflow definition.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
            home="entities/workflow-steps",
            strategy="id-local",
            default_status="active",
            statuses=["active", "superseded", "retired"],
        ),
        EntityKind(
            name="data-package",
            canonical_prefix="data-package",
            layer="layer/core",
            description="Frictionless research package containing analysis results, prose, and provenance metadata.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="research-package",
            canonical_prefix="research-package",
            layer="layer/core",
            description="Composed research package bundling analysis results and provenance.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="structural-chain",
            canonical_prefix="chain",
            layer="layer/core",
            description="Ordered structural decomposition: >=2 entity refs forming a chain whose verdicts are carried by chain-audit.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="chain-audit",
            canonical_prefix="chain-audit",
            layer="layer/core",
            description="Verdict over a structural-chain. Carries verdict+bayes_factor_evidence with enforced consistency.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="code-file",
            canonical_prefix="code-file",
            layer="layer/core",
            description="Source-code file implementing workflow steps and methods.",
            entity_class=EntityClass.OPERATIONAL,
            category=KindCategory.AUTHORED_CORE,
        ),
        EntityKind(
            name="evidence-line",
            canonical_prefix="evidence-line",
            layer="layer/core",
            description="A single, independence-tagged line of evidence that supports or disputes a proposition.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/evidence-lines",
            strategy="slug",
            default_status="draft",
            statuses=["draft", "active", "retired", "archived"],
        ),
        EntityKind(
            name="falsification",
            canonical_prefix="falsification",
            layer="layer/core",
            description="A structured record that a proposition-backed prediction was falsified.",
            entity_class=EntityClass.EPISTEMIC,
            category=KindCategory.AUTHORED_CORE,
            template_ready=True,
            home="entities/falsifications",
            strategy="slug",
            default_status="draft",
            statuses=["draft", "active", "retired", "archived"],
        ),
        EntityKind(
            name="unknown",
            canonical_prefix="unknown",
            layer="layer/core",
            description="Built-in sentinel kind for unrecognized entities.",
            entity_class=EntityClass.REFERENCE,
            category=KindCategory.RESERVED,
        ),
    ],
    relation_kinds=[
        RelationKind(
            name="tests",
            predicate="sci:tests",
            source_kinds=["task", "experiment", "workflow-run"],
            target_kinds=["hypothesis", "question"],
            layer="layer/core",
            description="Operational work tests a hypothesis or resolves a question.",
        ),
        RelationKind(
            name="blocked_by",
            predicate="sci:blockedBy",
            source_kinds=["task"],
            target_kinds=["task"],
            layer="layer/core",
            description="A task cannot proceed until another task is complete.",
        ),
        RelationKind(
            name="supports",
            predicate="cito:supports",
            source_kinds=["observation", "proposition", "evidence-line"],
            target_kinds=["proposition", "hypothesis"],
            layer="layer/core",
            description="An observation or proposition provides support for a proposition or hypothesis.",
        ),
        RelationKind(
            name="disputes",
            predicate="cito:disputes",
            source_kinds=["observation", "proposition", "evidence-line"],
            target_kinds=["proposition", "hypothesis"],
            layer="layer/core",
            description="An observation or proposition disputes a proposition or hypothesis.",
        ),
        RelationKind(
            name="addresses",
            predicate="sci:addresses",
            source_kinds=["question"],
            target_kinds=["proposition"],
            layer="layer/core",
            description="A question is addressed by a proposition.",
        ),
        RelationKind(
            name="executes",
            predicate="sci:executes",
            source_kinds=["workflow-run"],
            target_kinds=["workflow"],
            layer="layer/core",
            description="A workflow run executes a specific workflow.",
        ),
        RelationKind(
            name="applies",
            predicate="sci:applies",
            source_kinds=["workflow-step"],
            target_kinds=["method"],
            layer="layer/core",
            description="A workflow step applies an analytical method.",
        ),
        RelationKind(
            name="supersedes",
            predicate="sci:supersedes",
            source_kinds=["workflow-run", *_CONCLUSION_KINDS],
            target_kinds=["workflow-run", *_CONCLUSION_KINDS],
            allowed_kind_pairs=[
                RelationEndpointPair(source_kind="workflow-run", target_kind="workflow-run"),
                *_CONCLUSION_KIND_PAIRS,
            ],
            layer="layer/core",
            description=(
                "A newer entity replaces an older entity as canonical. Valid "
                "for workflow-run replacement and conclusion-level replacement."
            ),
        ),
        RelationKind(
            name="amends",
            predicate="sci:amends",
            source_kinds=_CONCLUSION_KINDS,
            target_kinds=_CONCLUSION_KINDS,
            allowed_kind_pairs=_CONCLUSION_KIND_PAIRS,
            layer="layer/core",
            description=(
                "A newer conclusion revises, narrows, qualifies, or extends an "
                "older conclusion without replacing it."
            ),
        ),
        RelationKind(
            name="feeds_into",
            predicate="sci:feedsInto",
            source_kinds=["workflow-step"],
            target_kinds=["workflow-step"],
            layer="layer/core",
            description="A workflow step feeds data into another step.",
        ),
        RelationKind(
            name="grounded_by",
            predicate="sci:groundedBy",
            source_kinds=["finding"],
            target_kinds=["data-package", "workflow-run"],
            layer="layer/core",
            description="A finding is grounded by a data package or workflow run.",
        ),
        RelationKind(
            name="synthesizes",
            predicate="sci:synthesizes",
            source_kinds=["story"],
            target_kinds=["interpretation", "discussion", "hypothesis"],
            layer="layer/core",
            description="A story synthesizes interpretations, discussions, or hypotheses.",
        ),
        RelationKind(
            name="organized_by",
            predicate="sci:organizedBy",
            source_kinds=["story"],
            target_kinds=["question", "hypothesis"],
            layer="layer/core",
            description="A story is organized around a question or hypothesis.",
        ),
        RelationKind(
            name="has_participant",
            predicate="sci:hasParticipant",
            source_kinds=["mechanism"],
            target_kinds=[],
            layer="layer/core",
            description="A mechanism points to its semantic participants.",
        ),
        RelationKind(
            name="has_proposition",
            predicate="sci:hasProposition",
            source_kinds=["mechanism"],
            target_kinds=["proposition"],
            layer="layer/core",
            description="A mechanism points to the propositions defining its claims.",
        ),
        RelationKind(
            name="grounds",
            predicate="sci:grounds",
            source_kinds=["workflow-run"],
            target_kinds=["observation"],
            layer="layer/core",
            description="A workflow run grounds an observation.",
        ),
        RelationKind(
            name="produced_by",
            predicate="sci:producedBy",
            source_kinds=["data-package", "dataset"],
            target_kinds=["workflow-run", "code-file"],
            layer="layer/core",
            description="A data artifact was produced by a workflow run or by code.",
        ),
        RelationKind(
            name="has_link",
            predicate="sci:hasLink",
            source_kinds=["structural-chain"],
            target_kinds=["mechanism", "model", "proposition", "observation", "finding"],
            layer="layer/core",
            description=(
                "Ordered structural-chain link. Targets are restricted to the "
                "structural building blocks. Order is carried in the materialized "
                "graph by sci:linkSequence (RDF list)."
            ),
        ),
        RelationKind(
            name="audits",
            predicate="sci:audits",
            source_kinds=["chain-audit"],
            target_kinds=["structural-chain"],
            layer="layer/core",
            description=(
                "A chain-audit asserts a verdict over a structural-chain. "
                "Mirrors the shape of `tests` (single target by convention)."
            ),
        ),
        RelationKind(
            name="bears_on",
            predicate="sci:bearsOn",
            source_kinds=[],
            target_kinds=[
                "assumption",
                "chain-audit",
                "discussion",
                "evidence-line",
                "finding",
                "hypothesis",
                "interpretation",
                "mechanism",
                "observation",
                "proposition",
                "question",
                "report",
                "story",
                "structural-chain",
                "theme",
                "validation-report",
            ],
            layer="layer/core",
            description=(
                "Source entity's state contributes to the evidence base of the "
                "target epistemic entity. Direction is upstream→downstream "
                "(evidence → belief). Auto-derived from typed edges and "
                "prov:wasDerivedFrom triples by the freshness engine; may also "
                "be hand-authored for cases the auto-rules miss."
            ),
        ),
        RelationKind(
            name="implements",
            predicate="sci:implements",
            source_kinds=["code-file"],
            target_kinds=["workflow-step", "method"],
            layer="layer/core",
            description="A code file implements a workflow step or method.",
        ),
        RelationKind(
            name="defines",
            predicate="sci:defines",
            source_kinds=["code-file"],
            target_kinds=["workflow"],
            layer="layer/core",
            description="A code file defines a workflow.",
        ),
        RelationKind(
            name="consolidates",
            predicate="sci:consolidates",
            source_kinds=["synthesis"],
            target_kinds=[],  # empty list = unrestricted target
            layer="layer/core",
            description="A cluster-digest synthesis consolidates the entities it absorbs (live → archived).",
        ),
    ],
)
