"""Core profile manifest for Science-native knowledge graph semantics."""

from science_model.profiles.schema import EntityKind, ProfileManifest, RelationKind

CORE_PROFILE = ProfileManifest(
    name="core",
    imports=[],
    strictness="core",
    entity_kinds=[
        EntityKind(
            name="hypothesis",
            canonical_prefix="hypothesis",
            layer="layer/core",
            description="Testable project hypothesis.",
        ),
        EntityKind(
            name="question",
            canonical_prefix="question",
            layer="layer/core",
            description="Open or resolved project question.",
        ),
        EntityKind(
            name="task",
            canonical_prefix="task",
            layer="layer/core",
            description="Operational project task tracked in the graph.",
        ),
        EntityKind(
            name="proposition",
            canonical_prefix="proposition",
            layer="layer/core",
            description="Truth-apt statement — the fundamental epistemic unit.",
        ),
        EntityKind(
            name="observation",
            canonical_prefix="observation",
            layer="layer/core",
            description="Concrete empirical fact anchored to specific data.",
        ),
        EntityKind(
            name="finding",
            canonical_prefix="finding",
            layer="layer/core",
            description="Unit of learned knowledge: propositions grounded by observations from an analysis.",
        ),
        EntityKind(
            name="interpretation",
            canonical_prefix="interpretation",
            layer="layer/core",
            description="One analysis session's narrative and its findings.",
        ),
        EntityKind(
            name="story",
            canonical_prefix="story",
            layer="layer/core",
            description="Coherent narrative arc synthesizing interpretations around a question or hypothesis.",
        ),
        EntityKind(
            name="paper",
            canonical_prefix="paper",
            layer="layer/core",
            description="Ordered composition of stories structured for communication.",
        ),
        EntityKind(
            name="experiment",
            canonical_prefix="experiment",
            layer="layer/core",
            description="Experiment or analysis step that tests project questions.",
        ),
        EntityKind(
            name="method",
            canonical_prefix="method",
            layer="layer/core",
            description="Analytical method or computational approach.",
        ),
        EntityKind(
            name="workflow",
            canonical_prefix="workflow",
            layer="layer/core",
            description="Reusable pipeline definition (Snakefile + config + rules).",
        ),
        EntityKind(
            name="workflow-run",
            canonical_prefix="workflow-run",
            layer="layer/core",
            description="Concrete execution of a workflow producing durable outputs.",
        ),
        EntityKind(
            name="workflow-step",
            canonical_prefix="workflow-step",
            layer="layer/core",
            description="Individual step within a workflow definition or run.",
        ),
        EntityKind(
            name="data-package",
            canonical_prefix="data-package",
            layer="layer/core",
            description="Frictionless research package containing analysis results, prose, and provenance metadata.",
        ),
    ],
    relation_kinds=[
        RelationKind(
            name="tests",
            predicate="sci:tests",
            source_kinds=["task", "experiment", "workflow-run"],
            target_kinds=["hypothesis", "question"],
            layer="layer/core",
            description="Operational work tests a hypothesis or resolves a question.",
        ),
        RelationKind(
            name="blocked_by",
            predicate="sci:blockedBy",
            source_kinds=["task"],
            target_kinds=["task"],
            layer="layer/core",
            description="A task cannot proceed until another task is complete.",
        ),
        RelationKind(
            name="supports",
            predicate="cito:supports",
            source_kinds=["observation", "proposition"],
            target_kinds=["proposition", "hypothesis"],
            layer="layer/core",
            description="An observation or proposition provides support for a proposition or hypothesis.",
        ),
        RelationKind(
            name="disputes",
            predicate="cito:disputes",
            source_kinds=["observation", "proposition"],
            target_kinds=["proposition", "hypothesis"],
            layer="layer/core",
            description="An observation or proposition disputes a proposition or hypothesis.",
        ),
        RelationKind(
            name="addresses",
            predicate="sci:addresses",
            source_kinds=["question"],
            target_kinds=["proposition"],
            layer="layer/core",
            description="A question is addressed by a proposition.",
        ),
        RelationKind(
            name="realizes",
            predicate="sci:realizes",
            source_kinds=["workflow"],
            target_kinds=["method"],
            layer="layer/core",
            description="A workflow is the executable realization of a method.",
        ),
        RelationKind(
            name="contains",
            predicate="sci:contains",
            source_kinds=["workflow", "finding", "interpretation"],
            target_kinds=["workflow-step", "proposition", "observation", "finding"],
            layer="layer/core",
            description="A workflow contains workflow steps; a finding or interpretation contains propositions, observations, or findings.",
        ),
        RelationKind(
            name="executes",
            predicate="sci:executes",
            source_kinds=["workflow-run"],
            target_kinds=["workflow"],
            layer="layer/core",
            description="A workflow run executes a specific workflow.",
        ),
        RelationKind(
            name="supersedes",
            predicate="sci:supersedes",
            source_kinds=["workflow-run"],
            target_kinds=["workflow-run"],
            layer="layer/core",
            description="A workflow run replaces a prior run.",
        ),
        RelationKind(
            name="feeds_into",
            predicate="sci:feedsInto",
            source_kinds=["workflow-step"],
            target_kinds=["workflow-step"],
            layer="layer/core",
            description="A workflow step feeds data into another step.",
        ),
        RelationKind(
            name="grounded_by",
            predicate="sci:groundedBy",
            source_kinds=["finding"],
            target_kinds=["data-package", "workflow-run"],
            layer="layer/core",
            description="A finding is grounded by a data package or workflow run.",
        ),
        RelationKind(
            name="synthesizes",
            predicate="sci:synthesizes",
            source_kinds=["story"],
            target_kinds=["interpretation"],
            layer="layer/core",
            description="A story synthesizes one or more interpretations.",
        ),
        RelationKind(
            name="organized_by",
            predicate="sci:organizedBy",
            source_kinds=["story"],
            target_kinds=["question", "hypothesis"],
            layer="layer/core",
            description="A story is organized around a question or hypothesis.",
        ),
        RelationKind(
            name="comprises",
            predicate="sci:comprises",
            source_kinds=["paper"],
            target_kinds=["story"],
            layer="layer/core",
            description="A paper comprises one or more stories.",
        ),
        RelationKind(
            name="grounds",
            predicate="sci:grounds",
            source_kinds=["workflow-run"],
            target_kinds=["observation"],
            layer="layer/core",
            description="A workflow run grounds an observation.",
        ),
        RelationKind(
            name="produced_by",
            predicate="sci:producedBy",
            source_kinds=["data-package"],
            target_kinds=["workflow-run"],
            layer="layer/core",
            description="A data package was produced by a specific workflow run.",
        ),
    ],
)
