"""Core profile manifest for Science-native knowledge graph semantics."""

from science_model.profiles.schema import EntityKind, ProfileManifest, RelationKind

CORE_PROFILE = ProfileManifest(
    name="core",
    imports=[],
    strictness="core",
    entity_kinds=[
        EntityKind(
            name="hypothesis",
            canonical_prefix="hypothesis",
            layer="layer/core",
            description="Testable project hypothesis.",
        ),
        EntityKind(
            name="question",
            canonical_prefix="question",
            layer="layer/core",
            description="Open or resolved project question.",
        ),
        EntityKind(
            name="task",
            canonical_prefix="task",
            layer="layer/core",
            description="Operational project task tracked in the graph.",
        ),
        EntityKind(
            name="claim",
            canonical_prefix="claim",
            layer="layer/core",
            description="Evidence-bearing project claim.",
        ),
        EntityKind(
            name="relation_claim",
            canonical_prefix="relation_claim",
            layer="layer/core",
            description="Claim whose content is an explicit subject-predicate-object relation.",
        ),
        EntityKind(
            name="experiment",
            canonical_prefix="experiment",
            layer="layer/core",
            description="Experiment or analysis step that tests project questions.",
        ),
        EntityKind(
            name="evidence",
            canonical_prefix="evidence",
            layer="layer/core",
            description="Evidence item that supports or disputes project claims.",
        ),
        EntityKind(
            name="method",
            canonical_prefix="method",
            layer="layer/core",
            description="Analytical method or computational approach.",
        ),
        EntityKind(
            name="workflow",
            canonical_prefix="workflow",
            layer="layer/core",
            description="Reusable pipeline definition (Snakefile + config + rules).",
        ),
        EntityKind(
            name="workflow-run",
            canonical_prefix="workflow-run",
            layer="layer/core",
            description="Concrete execution of a workflow producing durable outputs.",
        ),
        EntityKind(
            name="workflow-step",
            canonical_prefix="workflow-step",
            layer="layer/core",
            description="Individual step within a workflow definition or run.",
        ),
    ],
    relation_kinds=[
        RelationKind(
            name="tests",
            predicate="sci:tests",
            source_kinds=["task", "experiment", "workflow-run"],
            target_kinds=["hypothesis", "question"],
            layer="layer/core",
            description="Operational work tests a hypothesis or resolves a question.",
        ),
        RelationKind(
            name="blocked_by",
            predicate="sci:blockedBy",
            source_kinds=["task"],
            target_kinds=["task"],
            layer="layer/core",
            description="A task cannot proceed until another task is complete.",
        ),
        RelationKind(
            name="supports",
            predicate="cito:supports",
            source_kinds=["claim", "evidence"],
            target_kinds=["claim", "relation_claim", "hypothesis"],
            layer="layer/core",
            description="Evidence or a claim provides support for a claim or hypothesis.",
        ),
        RelationKind(
            name="disputes",
            predicate="cito:disputes",
            source_kinds=["claim", "evidence"],
            target_kinds=["claim", "relation_claim", "hypothesis"],
            layer="layer/core",
            description="Evidence or a claim disputes a claim or hypothesis.",
        ),
        RelationKind(
            name="realizes",
            predicate="sci:realizes",
            source_kinds=["workflow"],
            target_kinds=["method"],
            layer="layer/core",
            description="A workflow is the executable realization of a method.",
        ),
        RelationKind(
            name="contains",
            predicate="sci:contains",
            source_kinds=["workflow"],
            target_kinds=["workflow-step"],
            layer="layer/core",
            description="A workflow contains workflow steps.",
        ),
        RelationKind(
            name="executes",
            predicate="sci:executes",
            source_kinds=["workflow-run"],
            target_kinds=["workflow"],
            layer="layer/core",
            description="A workflow run executes a specific workflow.",
        ),
        RelationKind(
            name="supersedes",
            predicate="sci:supersedes",
            source_kinds=["workflow-run"],
            target_kinds=["workflow-run"],
            layer="layer/core",
            description="A workflow run replaces a prior run.",
        ),
        RelationKind(
            name="feeds_into",
            predicate="sci:feedsInto",
            source_kinds=["workflow-step"],
            target_kinds=["workflow-step"],
            layer="layer/core",
            description="A workflow step feeds data into another step.",
        ),
    ],
)
